# Generated by Django 4.2.3 on 2023-07-23 10:10

from django.db import migrations, models
import lynx.models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to=lynx.models.get_upload_file_name),
        ),
    ]
